[package]
name = "flowview-compiler-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
flowview-compiler = { path = "../crates/flowview-compiler" }
serde_json = "1.0"

[[bin]]
name = "compiler"
path = "fuzz_targets/compiler.rs"
test = false
doc = false
bench = false

[workspace]
